---
- hosts: web  #group name from the inventory
  
  vars:
    pack_name: httpd
    serv_name: httpd
  
  tasks:
    - name: Install {{ pack_name }}
      yum: pkg={{ pack_name }} state=installed
      become: yes
    - name: Start {{ serv_name }}
      service: name={{ serv_name }} state=started
      become: yes 

    - name: check Content
      shell: 'cat  /usr/share/httpd/noindex/index.html | grep  hELLO wORLD |wc -l' 
      register: output_content
    - debug: var=output_content

    - name: Ensure SELinux is set to enforcing mode
      lineinfile: 
        path: /usr/share/httpd/noindex/index.html
        regexp: 'hELLO wORLD'
        line: My name is Sumit
      become: yes
      notify: RESTART HTTPD
      when: output_content.stdout != "0"
  handlers:
    - name: RESTART HTTPD
      service: name={{ serv_name }} state=restarted
      become: yes
...
