---
- hosts: web
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: ec2-user 
        state: present
        key: "{{ lookup('file', '/home/ec2-user/.ssh/id_rsa.pub') }}"
